env:
    credentials: "ENCRYPTED[!ef153b13415d3e186733d124356bb48eacb07a158589c666e6533d9141267747dd0ab4f717c1d187307c43fff1d043f3!]"
    rcloneconfig: "ENCRYPTED[!66e1d22f2e1c0c00cc84e26b58dfa65f0be2e98eef8e25c0d28b2365412df31f6790c46cdcb80fab662fc094a28ac3ff!]"
    tokentl: "ENCRYPTED[!ca0248b8b7e05793ff1d8730f620cb425363ef6390e8fe0bf51a57b75d3962a1fc979fb41ba77178773ac56aeddfae5f!]"
    idtl: "ENCRYPTED[!37abc5b7be2c5a9b455a6f9eb06b35ec0e7d20b5ec581d4081e31e5e1a6f88ee832b3b95d4c0c5c733a0ea3b2544028d!]"
    lunch: lunch aospa_ginkgo-eng
    make: ./rom-build.sh ginkgo -t eng

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "Wrdn28"
       - git config --global user.email "ifloraxd@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy ginkgo:aospa/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync aospa Source"
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/pa-hk/manifest.git -b uvite -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/Wrdn28/local_manifest -b pa-14 .repo/local_manifests
      - rm -rf .repo/repo && git clone https://gerrit.googlesource.com/git-repo .repo/repo
 #     - sed -i 's|ssh://git@github.com|https://github.com|g' .repo/manifests/snippets/qassa.xml
#      - repoo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 --fail-fast
      - repo sync --current-branch --no-tags -j8
#      - sed -i 's| -u||g' vendor/qassa/config/branding.mk
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="Hirokixd"
      - export BUILD_HOSTNAME="HKprjkt"
      - export KBUILD_BUILD_USER="Hirokixd"
      - export KBUILD_BUILD_HOST="HKprjkt"
#      - export WITH_GAPPS=true
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Aospa for Ginkgo Started!"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/ginkgo/ && ls aospa*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz ginkgo:aospa -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"
#
